/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import controlador.*;
import dominio.*;
/**
 *
 * @author Antonio
 */
public class VentanaPersonal extends javax.swing.JFrame {
    Empresa registroActual;

    /**
     * Creates new form VentanaPersonal
     */
    public VentanaPersonal() {
        initComponents();
        this.setBounds(WIDTH, WIDTH, 400, 389);
        control Inicio = new control (this);
        Inicio.inicializarVentana(this,"src/imagenes/logo.jpg");
        control Iniciar = new control (empleados,dueno);
        control IniciarBotonAtras = new control (atras);
        Iniciar.activa_Desactiva_Button_Personal(true);
        IniciarBotonAtras.activa_Desactiva_Atras(true);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FondoPersonal = new javax.swing.JLabel();
        empleados = new javax.swing.JButton();
        dueno = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" MENU ADMINISTRACION");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personal.jpg"))); // NOI18N
        jPanel1.add(FondoPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, 210));

        empleados.setText(" LISTA EMPLEADOS");
        empleados.setOpaque(false);
        empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosActionPerformed(evt);
            }
        });
        jPanel1.add(empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 180, -1));

        dueno.setText("MENU DUEÑO");
        dueno.setOpaque(false);
        dueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duenoActionPerformed(evt);
            }
        });
        jPanel1.add(dueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 180, -1));

        atras.setText("<< ATRAS");
        atras.setOpaque(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 320, 350));

        FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FONDO INICIO_1.png"))); // NOI18N
        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -20, 520, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void duenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duenoActionPerformed
        // TODO add your handling code here:
        Ventanadueno ventana = new Ventanadueno ();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_duenoActionPerformed

    private void empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosActionPerformed
        // TODO add your handling code here:
        VentanaEmpleadosInstructores ventana = new VentanaEmpleadosInstructores ();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_empleadosActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        VentanaMenu ventana = new VentanaMenu ();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMenu;
    private javax.swing.JLabel FondoPersonal;
    private javax.swing.JButton atras;
    private javax.swing.JButton dueno;
    private javax.swing.JButton empleados;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
