/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import controlador.control;
import dominio.Empresa;
import java.util.*;
import javax.swing.ButtonGroup;
import dominio.Personal;
import dominio.Instructores;
import javax.swing.*;
import dominio.PersonalAdministrativo;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import registrar.*;
/**
 *
 * @author Antonio
 */
public class VentanaEmpleadosInstructores extends javax.swing.JFrame {
    Empresa registro;
    ArrayList<PersonalAdministrativo> Lista1;
    ArrayList<Instructores> Lista2;
    ButtonGroup grupo = new ButtonGroup();
    DatosEmpleadoXml datos = new DatosEmpleadoXml ();
    DatosInstructorXml datosIns = new DatosInstructorXml();

    /**
     * Creates new form VentanaEmpleadosInstructores
     */
    public VentanaEmpleadosInstructores() {
        initComponents();
        control inicio = new control (this);
        inicio.inicializarVentana(this, "src/imagenes/logo.jpg");
        control iniciar = new control (atras,opcionEmpleados,opcionInstructores,opcionTodos);
        iniciar.activa_Desactiva_Atras(true);
        grupoSeleccion();
        registro = inicio.devolverEmpresa();
        llenarTabla();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        atras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        opcionEmpleados = new javax.swing.JRadioButton();
        opcionInstructores = new javax.swing.JRadioButton();
        opcionTodos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EMPLEADOS E INSTRUCTORES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla.setEnabled(false);
        jScrollPane1.setViewportView(tabla);

        atras.setText("<< ATRAS");
        atras.setOpaque(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Archivero.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("EMPLEADOS E INSTRUCTORES");

        opcionEmpleados.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        opcionEmpleados.setText("EMPLEADOS");
        opcionEmpleados.setOpaque(false);
        opcionEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcionEmpleadosMousePressed(evt);
            }
        });
        opcionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEmpleadosActionPerformed(evt);
            }
        });

        opcionInstructores.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        opcionInstructores.setText("INSTRUCTORES");
        opcionInstructores.setOpaque(false);
        opcionInstructores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcionInstructoresMousePressed(evt);
            }
        });
        opcionInstructores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionInstructoresActionPerformed(evt);
            }
        });

        opcionTodos.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        opcionTodos.setText("TODOS");
        opcionTodos.setOpaque(false);
        opcionTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcionTodosMousePressed(evt);
            }
        });
        opcionTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(opcionEmpleados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opcionInstructores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opcionTodos)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(atras)
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcionInstructores)
                            .addComponent(opcionEmpleados)
                            .addComponent(opcionTodos))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atras)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 440, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FONDO INICIO_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        VentanaPersonal ventana = new VentanaPersonal ();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void grupoSeleccion (){
        grupo.add(opcionEmpleados);
        grupo.add(opcionInstructores);
        grupo.add(opcionTodos);
    }
    private void opcionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionEmpleadosActionPerformed

    private void opcionInstructoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionInstructoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionInstructoresActionPerformed

    private void opcionTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionTodosActionPerformed

    private void opcionEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionEmpleadosMousePressed
        // TODO add your handling code here:
        llenarTabla2();
    }//GEN-LAST:event_opcionEmpleadosMousePressed

    private void opcionInstructoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionInstructoresMousePressed
        // TODO add your handling code here:
        llenarTabla1();
    }//GEN-LAST:event_opcionInstructoresMousePressed

    private void opcionTodosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionTodosMousePressed
        // TODO add your handling code here:
        llenarTabla();
    }//GEN-LAST:event_opcionTodosMousePressed

    private void llenarTabla (){
        String[] columna = {"Cedula","Nombre y Apellido","Telefono"};
        DefaultTableModel p = new DefaultTableModel(null,columna);
        Lista1 = datos.cargarEmpleados();
        Lista2 = datosIns.cargarInstructores();
        for (Personal personal2 : Lista1){
            String[] row = {Long.toString(personal2.getCedulaEmpleado()),personal2.getNombreEmpleado(),Long.toString(personal2.getTelefonoEmpleado())};
            p.addRow(row);
        }
        for (Personal personal3 : Lista2){
            String[] row = {Long.toString(personal3.getCedulaEmpleado()),personal3.getNombreEmpleado(),Long.toString(personal3.getTelefonoEmpleado())};
            p.addRow(row);
        }
        tabla.setModel(p);
        
    }
    private void llenarTabla1 (){
        String[] columna = {"Cedula","Nombre y Apellido","Telefono"};
        DefaultTableModel p = new DefaultTableModel(null,columna);
        Lista2 = datosIns.cargarInstructores();
        for (Personal personal2 : Lista2){
            String[] row = {Long.toString(personal2.getCedulaEmpleado()),personal2.getNombreEmpleado(),Long.toString(personal2.getTelefonoEmpleado())};
            p.addRow(row);
        }
        tabla.setModel(p);
        p.fireTableDataChanged();
    }
    private void llenarTabla2 (){
        String[] columna = {"Cedula","Nombre y Apellido","Telefono"};
        DefaultTableModel p = new DefaultTableModel(null,columna);
        Lista1 = datos.cargarEmpleados();
        for (Personal personal2 : Lista1){
            String[] row = {Long.toString(personal2.getCedulaEmpleado()),personal2.getNombreEmpleado(),Long.toString(personal2.getTelefonoEmpleado())};
            p.addRow(row);
        }
        tabla.setModel(p);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleadosInstructores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleadosInstructores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleadosInstructores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleadosInstructores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEmpleadosInstructores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opcionEmpleados;
    private javax.swing.JRadioButton opcionInstructores;
    private javax.swing.JRadioButton opcionTodos;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
